//! Acceptance test for AC3 (MUST) — generated by `autobuilder scaffold`.
//!
//! Project: ambient (cli)
//! AC description: Throttles each voice with a per-voice minimum gap so a burst of incoming events of the same kind does not produce a burst of cues; defaults (seconds): chime 4, piano 8, settle 30, grain 15, drift 120, poly 30, silence 300. Suppressed events are dropped silently (no cue line emitted).
//! Test predicate: tests/acceptance_ac3_throttling.rs
//!
//! Ownership split: this //! header block (AC metadata) is
//! read-only — to change an AC, file
//! agent/intent_card_amendment_request.json and re-scaffold. The
//! `fn acceptance_ac3` body BELOW is owned by the edit-agent: replace
//! the panic stub with a real assertion that verifies the AC
//! description above.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::doc_markdown)]

#[test]
fn acceptance_ac3() {
    // edit-agent: replace this stub with a real assertion. The
    // panic keeps the test failing until you do, so the loop
    // sees a real Stage 3 signal.
    panic!("AC AC3 not yet implemented — see file header");
}
