//! Acceptance test for AC5 (MUST) — generated by `autobuilder scaffold`.
//!
//! Project: ambient (cli)
//! AC description: Per-voice throttle gap is configurable via CLI flags (e.g. --chime-secs, --piano-secs, --settle-secs, --grain-secs, --drift-secs, --poly-secs, --silence-secs); flags override the defaults.
//! Test predicate: tests/acceptance_ac5_cli_overrides.rs
//!
//! Ownership split: this //! header block (AC metadata) is
//! read-only — to change an AC, file
//! agent/intent_card_amendment_request.json and re-scaffold. The
//! `fn acceptance_ac5` body BELOW is owned by the edit-agent: replace
//! the panic stub with a real assertion that verifies the AC
//! description above.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::doc_markdown)]

#[test]
fn acceptance_ac5() {
    // edit-agent: replace this stub with a real assertion. The
    // panic keeps the test failing until you do, so the loop
    // sees a real Stage 3 signal.
    panic!("AC AC5 not yet implemented — see file header");
}
