//! Acceptance test for AC1 (MUST) — generated by `autobuilder scaffold`.
//!
//! Project: ambient (cli)
//! AC description: Reads newline-delimited JSON telemetry events from stdin and writes newline-delimited JSON cue events to stdout, one cue per accepted input event (subject to throttle/silence rules).
//! Test predicate: tests/acceptance_ac1_stdio_ndjson.rs
//!
//! Ownership split: this //! header block (AC metadata) is
//! read-only — to change an AC, file
//! agent/intent_card_amendment_request.json and re-scaffold. The
//! `fn acceptance_ac1` body BELOW is owned by the edit-agent: replace
//! the panic stub with a real assertion that verifies the AC
//! description above.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::doc_markdown)]

#[test]
fn acceptance_ac1() {
    // edit-agent: replace this stub with a real assertion. The
    // panic keeps the test failing until you do, so the loop
    // sees a real Stage 3 signal.
    panic!("AC AC1 not yet implemented — see file header");
}
